spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    username: b9aef16db746b0
    password: 872a8a60
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:weather_forecast
